[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino

monitor_speed = 115200

lib_deps =
    sauloverissimo/ESP32_Host_MIDI @ ^7.0.0
    lovyan03/LovyanGFX @ ^1.2.25
    lathoub/AppleMIDI @ ^3.3.0

; Formatierung: pio run -t format  (nutzt .clang-format)
extra_scripts = pre:scripts/format.py

; Statische Analyse: pio check
check_tool = cppcheck
check_flags =
    cppcheck: --enable=warning,style --inline-suppr --suppress=unusedFunction --suppress=*:*/.platformio/* --suppress=*:*/.pio/*
check_src_filters =
    +<src/>
    +<include/>
